[package]
name = "shared-build"
edition.workspace = true
authors.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true
license.workspace = true
include.workspace = true

[dependencies]
bindgen = { version = "0.71" }
